hud-data/kbnhud.json
Apologies for not reading through and adding these in the previous PR. Should be filled out to spec, alter as needed.
=> KBNHud - Added relevant traits and tags

hud-data/xhud.json
Updated hash to Xhud version released tonight.
=> Updated Xhud hash

hud-data/peachhud.json, hud-data/xhud.json
Updated Xhud hash and added ko-fi to support option for both.
=> Updated Xhud & PeachHUD

hud-data/xhud.json, hud-pages/xhud.md
=> Updated to Xhud v1.2.1-beta

hud-data/boredhud.json, hud-data/statichud.json, hud-data/voidhud-classic.json, hud-data/voidhud.json
Updated:
- boredHUD
- staticHUD
- voidHUD
- voidHUD Classic
=> Updated git hashes for my HUDs

hud-data/xhud.json
=> Updated Xhud

hud-data/middlemann.json
=> HUD update: middlemann

hud-data/mk-hud.json, hud-data/overwatch-hud.json
I changed my name from nimtra to kmarcie on GitHub. Changed the author name and link to repo to reflect this.
Hope I'm doing this right, lol
=> Updated mkhud and overwatch hud to have correct author name

hud-data/colourhud.json
=> Updated colourhud.json

hud-data/m0re-techno.json, hud-data/middlemann.json
m0re-techno - added some quake customization
middle mann - updated to latest commit with a lot of fixes (updating on the behalf of vexcenot since i also maintain the hud)
=> HUD update: m0re-techno // middle mann

hud-data/budhud.json
do wah diddy diddy dum diddy do
=> Bump budhud version to October release

hud-pages/keihud.md
Thanks for accepting my HUD by the way!
=> Fix typos in markdown for KeiHUD

hud-data/m0re-techno.json, hud-data/middlemann.json
m0re-techno: some new fonts and whatnot
middle mann: smissmas updates
=> HUD update: m0re-techno middlemann

hud-data/xhud.json, hud-pages/xhud.md
=> Xhud v2.0.0

hud-data/m0re-techno.json, hud-data/middlemann.json, hud-data/technohud.json
- added ctf tag 
- updated hash to latest commit
- updated hash to latest commit
- updated hash to latest commit
=> update maintained huds 

hud-data/technohud.json
0.341 (and any fixes i find along the way so i dont make multiple prs)
=> HUD update: technohud

hud-data/kbnhud.json
=> KBNHud update: v515

hud-data/middlemann.json, hud-data/technohud.json
- fixed health on resolutions above 2.5k or something
- some other misc things
- skinned koth a bit
- nuked player class model
=> HUD update: middlemann technohud

hud-data/m0re-techno.json, hud-data/middlemann.json, hud-data/technohud.json
* updated to m0rehud 7.2 
* added some fonts + other stuff
* updated to v21
* some fixes and whatnot
* minor changes to font files
=> HUD update: m0re-techno middlemann technohud

hud-data/peachhud.json
Updated PeachHUD to support 64 bit.
=> Updated PeachHUD

hud-data/garm3n-fm-ii.json, hud-data/m0re-techno.json, hud-data/middlemann.json, hud-data/mini-hud.json, hud-data/srshud.json, hud-data/technohud.json, hud-data/yesod-hud.json, hud-pages/yesod-hud.md
housekeeping mostly
only technohud, yesodhud and middle-mann got updates
bigger updates are on yesod hud with new readme
=> HUD update: like 17 huds

hud-data/technohud.json
https://github.com/tekunotri/technohud/commit/1983f113de676241a0488f03cd5a22f93c99aa95
=> technohud 0.38

hud-data/technohud.json
https://github.com/tekunotri/technohud/commit/1fb59f6abfc4214c54ad7a35693c85759649bcb3
=> technohud 0.39

hud-data/yesod-hud.json
Pushed a major update that fixed and added a lot of stuff.
- Added New Fonts
- Added Box for Low Ammo
- Simplified Ammo customization
- OG Backpack Customization
- Shadow Customization
- Spy Disguise Customization simplified
- New Crafting Icons
- Killfeed Icons Updated
- New TargetID Ammo Icon
- Chat Position Customization
- Tool UI Support (Name Tags, Paint Cans, etc.)
- Health/Ammo Repositioned
- New Backpack Icons
=> HUD update: yesod-hud

hud-data/m0re-techno.json, hud-data/technohud.json
=> HUD update: technohud m0re-techno

hud-data/ahud-cc.json
I am deeply sorry for pushing updates so frequently :((((
This time I fixed my f\*ck cfg that f\*ck movement in game
=> ahud-cc movement cfg hotfix

hud-data/middlemann.json
=> middlemann - update flags to be more accurate with what the hud actually has

hud-data/mk-hud.json, hud-data/overwatch-hud.json
=> Updated my HUDs to have the fixed proportional fonts (item context menu fonts & chat fonts)

hud-data/kbnhud.json
=> KBNHud update: v516

hud-data/512561891.json, hud-data/garm3n-fm-ii.json, hud-data/huehued.json, hud-data/m0re-techno.json, hud-data/middlemann.json, hud-data/mini-hud.json, hud-data/optive-hud.json, hud-data/srshud.json, hud-data/technohud.json, hud-data/yahud-fragvid.json
note: mostly just the context menus
=> sf24 updates to every hud i maintain/updated

hud-data/middlemann.json, hud-data/technohud.json
=> HUD update: m0re-techno technohud middlemann optivehud

hud-data/overwatch-hud.json
Just pushed a small update to the HUD. Thanks!
=> Updated overwatch HUD commit hash

hud-data/spacehud.json
https://github.com/BingBongBonky/SpaceHUD/releases/tag/1.5.0
=> Fixed multiple bugs in SpaceHUD

hud-data/kbnhud.json
=> Updated KBNHud to v517

hud-data/yesod-hud.json
Not trying to sound pushy, but this update was very big, stayed up all night for it. Most importantly, it hopefully solves a bunch of bugs people are having with my hud, especially with fonts.
Thanks,
yesod
=> Bigass update for yesodhud

hud-data/m0rehud.json
=> m0rehud hotfixes

hud-data/improved-default-hud.json
https://github.com/idhud-tf2/idhud/releases/tag/4.0.1
=> Update IDHUD to version 4.0.1
